name = "tictactoe-ws"
main = "serverless/websocket.js"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
    {name = "gameMatch", class_name="GameMatch"}
]


[[migrations]]
tag = "v1"
new_classes = ["GameMatch"]